# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = ""
name = ""
url = ""

[social.params]
icon = ""

[[social]]
identifier = ""
name = ""
url = ""

[social.params]
icon = ""
